id: P983B65BE
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: zh
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    25e0946783644d49978626bdd1f0ca40:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    d5b2cb735e494d009ebbad1235e29399:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    9be341e92edb47ed8b9929b9dc670172:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    92acdea30dea4a46852be2c96fca1866:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    a527862853f348f8a2bab5f5d3b4ba76:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    c055ec335f09403385a5239cb2fc5411:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    fa3641ccb197420aa7655d5c8f25640a:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    49ea6802d4ea4b7e913af2c7cc3b321e:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    a78d93334f274653b99f654736f02b5c:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    9a19ceb18d08455bbca0c5b134f1c4d0:
      title: The Lament of Rudra
      parent: Confession
    4ef92b39f74149fe902a6ff7015e5dae:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    18e147707cdf4c75987e462aedd5e44c:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    86e943ffe6b84265a8026a5ffe73859a:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    921bb846d0594d01a7f05dab08ea271d:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    b3f244a943534d788ce8efc21ac58315:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    1d5aead79d24478ca42561d8580d7396:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    4c706fc66cf340149d151371582c19f6:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    bb631d38993948c0931bdefb3967c598:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    c820e44048434b228d6685df874fd397:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    25b28f1e6c6e4807bd9c26c7f090f547:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    69e959011ed24a00916f92056f947130:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    b3ae044b4b10437f8ff00a5ea8366e8b:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    28c5822b1c8d4de1a649cf1327515b87:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    1a3cc62ff61d484e9ce4282f74232a64:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    a4bcb98e232f4aa58c1a517522cd62b3:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    c2f862a0a6da4f67b6e550cdaf6d4e51:
      title: The Twenty-Eight Commitments
      parent: Tantra
    97aa967cfc84422f8ca78352ff50b1d8:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.946985'
last_modified_at: '2022-02-28T22:46:47.946987'
